[parser]
url_link_key_escape = "\\>>>"
url_link_key = ">>>"
comment_key = "%"
comment_key_escape = "\\%"

[renderer]
from_lore_path = "./lore_src"
to_html_path = "./docs"
css_url = "../style.css"
lang = "zh-CN"
