[package]
name = "lore-pages"
version = "0.0.2"
edition = "2024"
authors = ["FleetingLore <macro__9@outlook.com>"]

description = "Lore Anchor for Pages"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/dotCorain/lore-pages"
repository = "https://github.com/dotCorain/lore-pages"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"
