# macOS 交叉编译 Linux: brew install FiloSottile/musl-cross/musl-cross
[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

# macOS 交叉编译 Windows: brew install mingw-w64
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
