[package]
name = "lang-impl"
version = "0.1.0"
edition = "2024"

[dependencies]
lang-core = { path = "../lang-core" }
lang-framework = { path = "../lang-framework" }
lang-parser = { path = "../lang-parser" }

[[example]]
name = "render_basic"
path = "examples/render_basic.rs"

[[example]]
name = "render_file"
path = "examples/render_file.rs"
