[package]
name = "lang-core"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]

[[example]]
name = "create_document"
path = "examples/create_document.rs"

[[example]]
name = "iterate_nodes"
path = "examples/iterate_nodes.rs"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
